### PR TITLE
Add 'hvc1' tag to x265/hevc videos

### PR DESCRIPTION
**Pull request by skeeet**
It makes Quicktime Player and Finder happy on Mac.

### CODE REVIEW

**Comment by henryruhs** [comment]
Hey, pull request only to the next branch... so this is macos only?

**Comment by skeeet** [comment]
@henryruhs >>

> Please explain "happy"

By default, Finder or QT won't open untagged x265 videos or show a preview. So adding proper metadata helps with that.
I'll create another PR for the "next" branch if you prefer.

**Comment by henryruhs** [comment]
Okay, but why is this related to the encoder? I could create a video on my AMD card and send it over to my MacOS friend?

**Comment by skeeet** [comment]
Well, you can encode video anywhere. It may be playable in QT player on OSX (VLC is fine with untagged, by the way), but that depends on how you create it. Some codec implementations explicitly tag it, and some don't.
This tag makes it more compatible with native OSX software.
See related discussions: https://discussions.apple.com/thread/253813055?sortBy=best and https://brandur.org/fragments/ffmpeg-h265

**Comment by henryruhs** [comment]
ok, but then this should be enough?

```
	if facefusion.globals.output_video_encoder in [ 'libx265' ]:
			commands.extend([ '-tag:v', 'hvc1' ])```

**Comment by skeeet** [comment]
It is needed for hevc_nvenc and x265 implementations (AMD stuff - no idea, but I'm 99% sure it is) and applies to anything using the H.265 standard and encoded with FFmpeg. 
Anyway, I guess we're having too long of a discussion over a trivial quality-of-life improvement, don't you think?

**Comment by henryruhs** [comment]
You are right, pull request closed...

**Pull request closed without merging**
