### PR TITLE
Update installer.py

### PR DESCRIPTION
**Pull request by johnnynunez**

### CODE REVIEW

**Comment by henryruhs** [comment]
I believe our installer is fine unless you are using ROCm 6.3

**Comment by johnnynunez** [comment]
> I believe our installer is fine unless you are using ROCm 6.3

It breaks with numpy version in your installer

**Comment by henryruhs** [comment]
I pushed a hotfix: https://github.com/facefusion/facefusion/commit/9f6000d20fd00d2e24fdf4688b5e616b406495ac

**Comment by johnnynunez** [comment]
> I pushed a hotfix: [9f6000d](https://github.com/facefusion/facefusion/commit/9f6000d20fd00d2e24fdf4688b5e616b406495ac) to use this wheels: https://repo.radeon.com/rocm/manylinux/rocm-rel-6.3.1/
> 
> Please give it a shot.

seems that onnxruntime rocm is still using numpy v1

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/toro/pinokio/api/facefusion-pinokio.git/facefusion/facefusion.py", line 7, in <module>
    from facefusion import core
  File "/home/toro/pinokio/api/facefusion-pinokio.git/facefusion/facefusion/core.py", line 9, in <module>
    from facefusion import content_analyser, face_classifier, face_detector, face_landmarker, face_masker, face_recognizer, logger, process_manager, state_manager, voice_extractor, wording
  File "/home/toro/pinokio/api/facefusion-pinokio.git/facefusion/facefusion/content_analyser.py", line 7, in <module>
    from facefusion import inference_manager, state_manager, wording
  File "/home/toro/pinokio/api/facefusion-pinokio.git/facefusion/facefusion/inference_manager.py", line 4, in <module>
    from onnxruntime import InferenceSession
  File "/home/toro/pinokio/api/facefusion-pinokio.git/.env/lib/python3.10/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "/home/toro/pinokio/api/facefusion-pinokio.git/.env/lib/python3.10/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found

**Comment by johnnynunez** [comment]
if onnxruntime_version < '1.19.0':


if onnxruntime_version <= '1.19.0':

**Comment by henryruhs** [comment]
Numpy 2.x support has been added since 1.19.0 and our installer should handle this.

**Comment by johnnynunez** [comment]
> Numpy 2.x support has been added since 1.19.0 and our [installer](https://github.com/facefusion/facefusion/blob/master/facefusion/installer.py#L92-L93) should handle this.
> 
> See: https://github.com/microsoft/onnxruntime/releases/tag/v1.19.0

yeah but I mean the onnxruntime rocm v1.19 is still compiled with numpy version v1. I tried and now it is working...

**Comment by henryruhs** [comment]
Does it make sense I switch my condition this way?

```
	if args.onnxruntime in [ 'rocm', 'directml' ]:
		subprocess.call([ shutil.which('pip'), 'install', 'numpy==1.26.4', '--force-reinstall' ])```

**Comment by johnnynunez** [comment]
> I pushed another condition to master:
> 
> ```
> if args.onnxruntime in [ 'rocm', 'directml' ]:
> 	subprocess.call([ shutil.which('pip'), 'install', 'numpy==1.26.4', '--force-reinstall' ])
> ```
> 
> It's just a bit tricky not to forget about it on future updates.

now it's working! thanks

**Comment by henryruhs** [comment]
Great

**Pull request closed without merging**
