### PR TITLE
ci.yml: pip now has a real dependency resolver

### PR DESCRIPTION
**Pull request by cclauss**
Provide pip with all dependencies so it can properly resolve conflicts.
* https://pip.pypa.io/en/stable/topics/dependency-resolution

### CODE REVIEW

**Comment by henryruhs** [comment]
I prefer to keep it the way it is for better readability, but thanks for the PR - in case we have resolve issues I know how to resolve it.

PS: send PRs to the next branch only

**Comment by cclauss** [comment]
There is highly debatable readability vs. highly provable CPU cycles.  As the URL explains, you won't resolve dependency problems.  Pip will always do so but it will do so much slower if they are fed to it one at a time.  Much work has gone into creating the resolver so it is a shame to circumvent it.  Pip's resolution time might be minimal for only three deps but will grow as more deps are added so one-by-one is a bad habit to get into.

I detest repos where the default branch is not the contribution branch. This counterintuitive approach only fosters frustration.

**Comment by henryruhs** [comment]
Default branch should be the stable one that users are seeing, but I get your point.

**Comment by cclauss** [comment]
Thanks.  If each [release](https://github.com/facefusion/facefusion/releases) is a branch then users can always see the contents any release.  This allows developers to continue work on default branch.

**Pull request closed without merging**
