### PR TITLE
Create setup.py

### PR DESCRIPTION
**Pull request by zeitgeistf**

### CODE REVIEW

**Comment by zeitgeistf** [comment]
> I understand but why do we need it? This is not a package being released on pip...

Hi @henryruhs thank you for the extremely fast response.
Do you have any plan releasing this at some point? We really like your work and would like to use it if it's available by any chance

**Comment by henryruhs** [comment]
There is no plan to extract a library from FF for various reason that I don't plan to discuss in public. Sorry

**Comment by zeitgeistf** [comment]
> There is no plan to extract a library from FF for various reasons that I don't plan to discuss in public. Sorry

Understood, thank you

**Comment by henryruhs** [comment]
You can reach out via Discord if you like to know.

**Pull request closed without merging**
