### PR TITLE
Add WebCam Device choices

### PR DESCRIPTION
**Pull request by MoLeft**

### CODE REVIEW

**Comment by henryruhs** [comment]
thanks for the PR.

1. always request to push to the next branch instead of the master
2. we try to avoid third party dependencies and especially those from (sorry) unpopular developers that (sorry) did not maintain their project for a while

can you find another way? probably brute force opening the devices via cv2.VideoCapture?

**Comment by MoLeft** [comment]
> thanks for the PR.
> 
> 1. always request to push to the next branch instead of the master
> 2. we try to avoid third party dependencies and especially those from (sorry) unpopular developers that (sorry) did not maintain their project for a while
> 
> can you find another way? probably brute force opening the devices via cv2.VideoCapture?

Maybe I can try it.

**Comment by henryruhs** [comment]
Reach out via Discord so we can align.

**Comment by henryruhs** [comment]
Please open a new PR to next - that one is causing merge conflicts. Thanks

**Pull request closed without merging**
